
-----DATA PREPARATION AND UNDERSTANDING-------
------Q1..What is the total number of rows in each of the 3 tables in the database?
select count(customer_Id) as count_customer
from Customer

select COUNT(prod_cat_code) as count_prod_cat_info
from prod_cat_info

select COUNT(transaction_id) as count_transaction_id
from Transactions

----------
-----Q2....What is the total number of transactions that have a return?
select count(total_amt)[no_of_transaction]
from Transactions
where total_amt < 0
------
-----Q3....As you would have noticed, the dates provided across the datasets are not in a correct format.
-- As first steps, pls convert the date variables into valid date formats before proceeding ahead.
alter table customer
alter column DOB date;
alter table transactions
alter column tran_date date;
-------
------Q4...What is the time range of the transaction data available for analysis? Show the output in number of days, months and years
--      simultaneously in different columns.
select distinct 
datediff("day",(select min(tran_date) from Transactions),(select max(tran_date) from Transactions))[time_range_in_days],
datediff("month",(select min(tran_date) from Transactions),(select max(tran_date) from Transactions))[time_range_in_months],
datediff("year",(select min(tran_date) from Transactions),(select max(tran_date) from Transactions))[time_range_in_years]
------------
-------Q5...Which product category does the sub-category “DIY” belong to?
select prod_cat
from prod_cat_info
where prod_subcat ='DIY'
--------
------DATA ANALYSIS
----Q1.Which channel is most frequently used for transactions?
select top 1 store_type,count(store_type)[most_used_transaction]
from transactions
group by store_type
order by count(store_type) desc
-------
-----Q2...What is the count of Male and Female customers in the database?
select  gender,COUNT(gender)
from Customer
group by Gender
--------
-----Q3..From which city do we have the maximum number of customers and how many? 
select city_code,max(customer_id)[max]
from Customer
group by city_code
------
-----Q4..How many sub-categories are there under the Books category?
select prod_cat, count(prod_subcat)[count_of_subcat]
from prod_cat_info
where prod_cat = 'books'
group by prod_cat
--------
-----Q5..What is the maximum quantity of products ever ordered?
select prod_cat_code,max(qty)[max_of_qty_prod]
from Transactions
group by prod_cat_code
--------
-----Q6...What is the net total revenue generated in categories Electronics and Books?
select prod_cat, sum(total_amt)[net_revenue]
from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
where prod_cat in ('electronics','books') 
group by prod_cat
-------
----Q7...How many customers have >10 transactions with us, excluding returns?
select cust_id,count(transaction_id)[count_of_transcations]
from Transactions
group by cust_id
having count(transaction_id) > 10 
------
-----Q8..What is the combined revenue earned from the “Electronics” & “Clothing” categories, from “Flagship stores”?
select sum(total_amt)[combined_revenue]
from(select total_amt,store_type
     from prod_cat_info p inner join Transactions t on p.prod_cat_code=t.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code
	 where prod_cat in ('electronics','clothing'))s1
where Store_type='flagship store'
------
-----Q9.What is the total revenue generated from “Male” customers in “Electronics” category? Output should display total revenue by prod sub-cat.
select sum(total_amt)[total_revenue],prod_subcat
from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code and p.prod_sub_cat_code=t.prod_subcat_code inner join customer c on t.cust_id=c.customer_id
where  prod_cat ='electronics' and  gender='M'
group by prod_subcat
------
---Q10..What is percentage of sales and returns by product sub category; display only top 5 sub categories in terms of sales?
select top 5 prod_subcat,(SUM(qty)*100/(select sum(qty) from Transactions))[Return_by_percentage],
(sum(total_amt)*100/(select sum(total_amt) from transactions))[Sales_percentage],
sum(total_amt)[Total_sales]
from prod_cat_info P INNER JOIN Transactions T ON P.prod_cat_code=T.prod_cat_code AND P.prod_sub_cat_code=T.prod_subcat_code
group by prod_subcat
order by sum(total_amt) desc
-----
-----Q11..For all customers aged between 25 to 35 years find what is the net total revenue generated by these consumers in last 
----- 30 days of transactions from max transaction date available in the data?
select sum(total_amt)[net_total_revenue]
from Transactions t inner join Customer c on t.cust_id=c.customer_Id
where year(tran_date)-year(DOB) between '25' and '35' and tran_date > DATEADD(dd,-30,(select max(tran_date) from transactions))
-------
------Q12.Which product category has seen the max value of returns in the last 3 months of transactions?
select top 1 prod_cat,sum(total_amt)[return_value]
from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
where total_amt < 0 and tran_date > DATEADD(mm,-3,(select max(tran_date) from transactions))
group by prod_cat
order by sum(total_amt) asc
-----
-----Q13..Which store-type sells the maximum products; by value of sales amount and by quantity sold?
select top 1 store_type, sum(total_amt)[by_sales],sum(qty)[by_qty_sold]
from Transactions
group by Store_type
order by by_sales desc,by_qty_sold desc
--------
----Q14.What are the categories for which average revenue is above the overall average.
select prod_cat,avg(total_amt)[individual_avg]
from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code
group by prod_cat
having avg(total_amt) > (select avg(total_amt)[overall_avg] from Transactions)
------
------Q15..Find the average and total revenue by each subcategory for the categories which are among top 5 categories in terms of quantity sold.
select top 5 p.prod_cat,p.prod_subcat,avg(t.total_amt)[avg_revenue],sum(t.total_amt)[total_revenue],sum(t.qty)[total_qty]
from Transactions t inner join prod_cat_info p on t.prod_cat_code=p.prod_cat_code and t.prod_subcat_code=p.prod_sub_cat_code
group by p.prod_cat,p.prod_subcat
order by sum(t.qty) desc
-------



































































































































































































































































































































































































































































































































































































































































































































